config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'root#index'

  resources :domains, only: %i[create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/domains_controller.rb
# frozen_string_literal: true

require 'net/http'

class DomainsController < ApplicationController
  def create
    domain_name = domain_params[:name]

    if domain_name.empty?
      flash.now[:error] = 'Укажите адрес'
      render 'root/index', status: :unprocessable_entity
      return
    end
    uri = URI(domain_params[:name])
    response = Net::HTTP.get_response(uri)

    if fail?
      raise 'Упс! Что-то пошло не так'
    end

    if response.is_a?(Net::HTTPSuccess)
      redirect_to :root, { notice: 'Ура! Сайт успешно проверен и никакой ошибки не произошло' }
      return
    end

    redirect_to :root, flash: { error: 'Упс! Кажется сайт не отвечает' }
  end

  private

  def domain_params
    params.require(:domain).permit(:name)
  end

  def fail?
    rand(1..5) == 5
  end
end

app/controllers/root_controller.rb
# frozen_string_literal: true

class RootController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def map_alert_type(type)
    map = {
      notice: 'info',
      error: 'danger',
      success: 'success'
    }
    map.fetch(type.to_sym, 'info')
  end
end

app/helpers/domains_helper.rb
# frozen_string_literal: true

module DomainsHelper
end

app/helpers/root_helper.rb
# frozen_string_literal: true

module RootHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Тестовое приложение
    meta[name='viewport' content='width=device-width,initial-scale=1']
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true
  body
    = yield

app/views/root/index.html.slim
body.min-vh-100.d-flex.flex-column
  - flash.each do |type, msg|
    div class=class_names('alert', "alert-#{map_alert_type(type)}") role='alert'
      = msg
  main.flex-grow-1
    .container-lg.mt-3
      h1
      .row
        .col-12.col-md-10.col-lg-8.mx-auto.border.rounded-3.bg-light.p-5
          h1.display-3 Пинг-понг
          p.lead.text-nowrap
            | Эта форма проверит сайт на доступность. Конечно, если не ничего не произойдет 🤔
          = simple_form_for :domain, url: domains_path, data: { turbo: false }, html: { class: :row } do |f|
              .col-md-8.align-self-center
                = f.input :name, label: 'Адрес', placeholder: 'https://google.ru/', hint: 'Введите адрес сайта, например https://google.ru/'
              .col-md-2.align-self-center
                = f.submit 'Отправить', class: 'btn btn-primary btn-lg text-uppercase'

  footer.border-top.py-3.mt-5.flex-shrink-0
    .container-lg
      .text-center
        a href="https://hexlet.io" target="_blank"  Hexlet